### PR TITLE
Quick fixes to update docs and modules

### PR DESCRIPTION
**Pull request by sdhutchins**

### CODE REVIEW

**Comment by sdhutchins** [comment]
@grabear I'm leaving this open to make some quick fixes. If you want to check out this branch, you can.

**Comment by grabear** [comment]
Are you ready to merge? @sdhutchins

**Comment by sdhutchins** [comment]
@grabear No, not nearly unfortunately. I need to step away for about an hour. I'm trying to redo the docs a bit.

**Comment by sdhutchins** [comment]
Actually, go ahead and merge.

I got the docs to a stopping point. http://orthoevolution.readthedocs.io/en/quick-fixes/

**Pull request merged**
